### ISSUE TITLE
O(n) SOLUTION

### ISSUE THREAD

**Issue by Bobzero23** [yapicimurat/leetcode#1]
I think is possible to write O(n) solution for the 219. Contains Duplicate II

**Comment by Bobzero23** [comment]
@yapicimurat I can solve this issue please assign me

**Comment by yapicimurat** [comment]
> I think is possible to write O(n) solution for the 219. Contains Duplicate II

Ok, bro. I'm waiting for your contribution. thanks in advance.
I created a branch for your contribution.

**Comment by Bobzero23** [comment]
> > I think is possible to write O(n) solution for the 219. Contains Duplicate II
> 
> Ok, bro. I'm waiting for your contribution. thanks in advance. I created a branch for your contribution.

I say the new branch you created. Thanks for that, I am currently working on the solution.

**Comment by Bobzero23** [comment]
@yapicimurat I have created a pull request in the new branch please feel free to check it out. I hope I did it well.
